### ISSUE TITLE
Problems with code in pgb-pong-pytorch and pg-pong-pytorch

### ISSUE THREAD

**Issue by xlyue92** [ucla-rlcourse/RLexample#11]
Hi, I assumed there are some errors with the above two algorithms codes. Basically, they are similar.

In both of them, Professor used "args.batch_size" to update model params every batch_size episodes, this corresponds to what was presented in professor's lecture slide 5. But in the defined function: finish_episode(), G is calculated for every single episode, I guess you might forget to separate rewards in each episode since you also commented in the ac-pong codes and flatten rewards and values you defined for calculation. 

If the model is updated every batch_size time, then policy.rewards should append a [] for every episode separately. Hope my understanding is correct.

**Comment by Moondok** [comment]
I agree with you. In the following snippet:
```for r in policy.rewards[::-1]:
        R = r + args.gamma * R
        rewards.insert(0, R)```
the `rewards` variable contains rewards of a minibatch instead of a single episode. Hope my understanding is correct.
